server:
  port: 8080

#spring:
#  datasource:
#    username: shanglei
#    password: shanglei008
#    jdbc-url: jdbc:mysql://114.55.239.78:3307/jdcos
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialSize: 5
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
#    druid:
    username: shanglei
    password: shanglei008
    driver-class-name: com.mysql.jdbc.Driver  # mysql8.0以前使用com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://114.55.239.78:3307/jdcos
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000