#app:
#  datasource:
#    url: jdbc:mysql://192.168.1.6:3307/pigxx
#    username: root
#    password: 123456
#    pool-size: 2

server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:123456}
      url: jdbc:mysql://${MYSQL-HOST:192.168.1.6}:${MYSQL-PORT:3307}/${MYSQL-DB:pigxx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
